//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoxcoinEntities : DbContext
    {
        public BoxcoinEntities()
            : base("name=BoxcoinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntidadSet> EntidadSet { get; set; }
        public virtual DbSet<menu_opciones> menu_opciones { get; set; }
        public virtual DbSet<pepito> pepito { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<permisos_por_rol> permisos_por_rol { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<roles_por_usuario> roles_por_usuario { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
